export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILSREQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILSSUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILSFAIL";
export const ERROR_NULL = "ERROR_NULL";
